/*
 * Copyright (c) 2014 WISE.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    WISE - initial API and implementation and/or initial documentation
 */
package app.view.atleta;

import app.controller.AtividadeController;
import app.controller.AtletaController;
import app.controller.ContaController;
import app.view.atletaAtividade.AtletaAtividadeView;
import conf.Global;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author WISE
 */
public class AtletaView extends javax.swing.JDialog {

    private final AtletaController ac;
    public int linhaSelecionada = 0;
    public static int matricula = 0;
    public static int atletaId = 0;
    public static String Selecionado = "";

    /**
     * Creates new form AtletaView
     */
    public AtletaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ac = new AtletaController();
        atletaTabela.setModel(ac.listar());
        atletaTabela.getColumnModel().getColumn(0).setPreferredWidth(10); //Mat.
        atletaTabela.getColumnModel().getColumn(1).setPreferredWidth(150); //Nome.
        atletaTabela.getColumnModel().getColumn(2).setPreferredWidth(80); //RG.
        atletaTabela.getColumnModel().getColumn(3).setPreferredWidth(2); //Ativo.

        TableCellRenderer defaultRenderer = atletaTabela.getDefaultRenderer(Object.class);
        TableCellRenderer r = new AtletaCellRender(defaultRenderer);

        atletaTabela.getColumnModel().getColumn(3).setCellRenderer(r);

        int qtdAtivo = 0, qtdDesativado = 0;
        for (int i = 0; i < atletaTabela.getModel().getRowCount(); i++) {
            if (atletaTabela.getModel().getValueAt(i, 3).equals("S")) {
                qtdAtivo++;
            } else {
                qtdDesativado++;
            }

        }

        totalAtletas.setText(String.valueOf(atletaTabela.getModel().getRowCount()));
        ativos.setText(String.valueOf(qtdAtivo));
        desativados.setText(String.valueOf(qtdDesativado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pesquisaTxt = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atletaTabela = new javax.swing.JTable();
        cadastrarBt = new javax.swing.JButton();
        editarBt = new javax.swing.JButton();
        atividadeBt = new javax.swing.JButton();
        fecharBt = new javax.swing.JButton();
        removerBt = new javax.swing.JButton();
        nomeRadio = new javax.swing.JRadioButton();
        matRadio = new javax.swing.JRadioButton();
        financeiroBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalAtletas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ativos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desativados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atletas");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        atletaTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        atletaTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atletaTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(atletaTabela);

        cadastrarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-walking.png"))); // NOI18N
        cadastrarBt.setText("Cadastrar");
        cadastrarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtActionPerformed(evt);
            }
        });

        editarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-pencil.png"))); // NOI18N
        editarBt.setText("Editar");
        editarBt.setEnabled(false);
        editarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtActionPerformed(evt);
            }
        });

        atividadeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-digg2.png"))); // NOI18N
        atividadeBt.setText("Atividades");
        atividadeBt.setEnabled(false);
        atividadeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividadeBtActionPerformed(evt);
            }
        });

        fecharBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cross.png"))); // NOI18N
        fecharBt.setText("Fechar");
        fecharBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtActionPerformed(evt);
            }
        });

        removerBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-trash.png"))); // NOI18N
        removerBt.setText("Remover");
        removerBt.setEnabled(false);
        removerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtActionPerformed(evt);
            }
        });

        buttonGroup1.add(nomeRadio);
        nomeRadio.setSelected(true);
        nomeRadio.setText("Nome");

        buttonGroup1.add(matRadio);
        matRadio.setText("Mat.");

        financeiroBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money_bag.png"))); // NOI18N
        financeiroBt.setText("Financiero");
        financeiroBt.setEnabled(false);
        financeiroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeiroBtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total de atletas:");

        totalAtletas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalAtletas.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ativos:");

        ativos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ativos.setForeground(new java.awt.Color(51, 51, 255));
        ativos.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Desativados:");

        desativados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        desativados.setForeground(new java.awt.Color(255, 51, 51));
        desativados.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecharBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atividadeBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastrarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removerBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(financeiroBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pesquisaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(matRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalAtletas)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ativos)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(desativados)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(nomeRadio)
                    .addComponent(matRadio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cadastrarBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atividadeBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(financeiroBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecharBt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalAtletas)
                    .addComponent(jLabel2)
                    .addComponent(ativos)
                    .addComponent(jLabel3)
                    .addComponent(desativados))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtActionPerformed
        this.setModal(false);
        AtletaCadastro ac = new AtletaCadastro(null, true);
        ac.setVisible(true);
    }//GEN-LAST:event_cadastrarBtActionPerformed

    private void fecharBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtActionPerformed
        linhaSelecionada = 0;
        matricula = 0;
        atletaId = 0;
        Selecionado = "";

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fecharBtActionPerformed

    private void editarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtActionPerformed
        AtletaController ac = new AtletaController();
        AtletaController.linhaSelecionadaTabelela = linhaSelecionada;
        ac.editar(matricula);

        matricula = 0;

        editarBt.setEnabled(false);
        removerBt.setEnabled(false);
        atividadeBt.setEnabled(false);
        financeiroBt.setEnabled(false);
    }//GEN-LAST:event_editarBtActionPerformed

    private void atletaTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atletaTabelaMouseClicked

        if (atletaTabela.getModel().getRowCount() > 0) {
            linhaSelecionada = atletaTabela.getSelectedRow();
            int coluna = atletaTabela.getSelectedColumn();
            int count = evt.getClickCount();

            matricula = (int) atletaTabela.getModel().getValueAt(linhaSelecionada, 0);

            editarBt.setEnabled(true);
            removerBt.setEnabled(true);
            atividadeBt.setEnabled(true);
            financeiroBt.setEnabled(true);

            if (count > 1) {
                AtletaController ac = new AtletaController();
                AtletaController.linhaSelecionadaTabelela = linhaSelecionada;
                ac.editar(matricula);

            }
        }
    }//GEN-LAST:event_atletaTabelaMouseClicked

    private void atividadeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividadeBtActionPerformed
        AtividadeController avc = new AtividadeController();
        AtletaAtividadeView atv = new AtletaAtividadeView(null, true);
        AtletaCadastro.seDesejaColocarAtividade = "N";
        atv.setVisible(true);
        avc.listarAtletaAtividade(matricula);

    }//GEN-LAST:event_atividadeBtActionPerformed

    private void removerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtActionPerformed
        AtletaController ac = new AtletaController();
        int dialogResultado = JOptionPane.showConfirmDialog(null, "Deseja realmente remover?");
        if (dialogResultado == JOptionPane.YES_OPTION) {
            ac.deletar(matricula, linhaSelecionada);
            removerBt.setEnabled(false);
            editarBt.setEnabled(false);
            atividadeBt.setEnabled(false);
            financeiroBt.setEnabled(false);
        }
    }//GEN-LAST:event_removerBtActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String pesquisa = pesquisaTxt.getText();

        if (nomeRadio.isSelected() == true) {
            Selecionado = "nome";
        }

        if (matRadio.isSelected() == true) {
            Selecionado = "matricula";
        }

        AtletaController ac = new AtletaController();
        ac.filtrar(pesquisa, Selecionado);

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void financeiroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeiroBtActionPerformed
        ContaController cc = new ContaController();
        cc.chamarView(matricula);

    }//GEN-LAST:event_financeiroBtActionPerformed

    public void pesqAtualizar() {
        java.awt.event.ActionEvent evt = null;
        btPesquisarActionPerformed(evt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (Global.TEMA.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtletaView dialog = new AtletaView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atividadeBt;
    private javax.swing.JLabel ativos;
    public static javax.swing.JTable atletaTabela;
    public static javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastrarBt;
    private javax.swing.JLabel desativados;
    private javax.swing.JButton editarBt;
    private javax.swing.JButton fecharBt;
    private javax.swing.JButton financeiroBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton matRadio;
    private javax.swing.JRadioButton nomeRadio;
    private javax.swing.JTextField pesquisaTxt;
    private javax.swing.JButton removerBt;
    private javax.swing.JLabel totalAtletas;
    // End of variables declaration//GEN-END:variables
}
