/*
 * Copyright (c) 2014 WISE.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    WISE - initial API and implementation and/or initial documentation
 */
package app.view.contas;

import app.controller.ContaController;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import libs.Validador;

/**
 *
 * @author WISE
 */
public class ContasResumo extends javax.swing.JDialog {

    private ContaController cc;

    /**
     * Creates new form ContasResumo
     */
    public ContasResumo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dataInicioTxt = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        dataFimTxt = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalhesTabela = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        registroPagos = new javax.swing.JLabel();
        valorTotalRegistrosPagos = new javax.swing.JLabel();
        registrosAbertos = new javax.swing.JLabel();
        valorTotalregistrosAbertos = new javax.swing.JLabel();
        registrosVencidos = new javax.swing.JLabel();
        valorTotalRegistrosVencidos = new javax.swing.JLabel();
        valorTotalTudo = new javax.swing.JLabel();
        valorTotalRecebido = new javax.swing.JLabel();
        totalRegistros = new javax.swing.JLabel();
        carregarBt = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        fechatBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resumo mensal");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo mensal"));

        jLabel1.setText("Data Início");

        jLabel2.setText("Data Fim");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabel3.setText("Registros:");

        jLabel4.setText("Registros Pagos:");

        jLabel5.setText("Registros em aberto:");

        jLabel6.setText("Registros vencidos:");

        jLabel7.setText("Valor total:");

        jLabel8.setText("Valor total:");

        jLabel9.setText("Valor total:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Valor total estimado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Valor total recebido:");

        detalhesTabela.setModel(new javax.swing.table.DefaultTableModel(

        ));
        jScrollPane1.setViewportView(detalhesTabela);

        jLabel12.setText("Detalhes");

        registroPagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registroPagos.setForeground(new java.awt.Color(51, 51, 255));
        registroPagos.setText("0");

        valorTotalRegistrosPagos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalRegistrosPagos.setForeground(new java.awt.Color(51, 51, 255));
        valorTotalRegistrosPagos.setText("0");

        registrosAbertos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrosAbertos.setForeground(new java.awt.Color(51, 51, 255));
        registrosAbertos.setText("0");

        valorTotalregistrosAbertos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalregistrosAbertos.setForeground(new java.awt.Color(51, 51, 255));
        valorTotalregistrosAbertos.setText("0");

        registrosVencidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrosVencidos.setForeground(new java.awt.Color(255, 51, 51));
        registrosVencidos.setText("0");

        valorTotalRegistrosVencidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalRegistrosVencidos.setForeground(new java.awt.Color(255, 51, 51));
        valorTotalRegistrosVencidos.setText("0");

        valorTotalTudo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalTudo.setForeground(new java.awt.Color(51, 51, 255));
        valorTotalTudo.setText("0");

        valorTotalRecebido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalRecebido.setForeground(new java.awt.Color(255, 51, 51));
        valorTotalRecebido.setText("0");

        totalRegistros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegistros.setForeground(new java.awt.Color(51, 51, 255));
        totalRegistros.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorTotalTudo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotalRecebido))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalRegistros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valorTotalRegistrosPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(registroPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrosAbertos)
                                    .addComponent(valorTotalregistrosAbertos))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrosVencidos)
                                    .addComponent(valorTotalRegistrosVencidos)))
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(totalRegistros))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(registroPagos)
                            .addComponent(registrosAbertos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(valorTotalRegistrosPagos)
                            .addComponent(jLabel7)
                            .addComponent(valorTotalregistrosAbertos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(registrosVencidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(valorTotalRegistrosVencidos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(valorTotalTudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(valorTotalRecebido))
                .addGap(53, 53, 53))
        );

        carregarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-check.png"))); // NOI18N
        carregarBt.setText("Carregar");
        carregarBt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarBtActionPerformed(evt);
            }
        });

        jLabel13.setText("Resultados baseado na data de vencimento de cada conta.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(dataInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dataFimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(carregarBt))))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataFimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carregarBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fechatBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cross.png"))); // NOI18N
        fechatBt.setText("Fechar");
        fechatBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechatBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fechatBt)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechatBt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarBtActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        SimpleDateFormat formatter;

        if (dataInicioTxt.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Data incial não pode ser em branco", "Erros", JOptionPane.ERROR_MESSAGE);
        } else if (dataFimTxt.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Data final não pode ser em branco", "Erros", JOptionPane.ERROR_MESSAGE);
        } else {

            formatter = new SimpleDateFormat("yyyy-MM-dd");

            String dataStringInicio = formatter.format(dataInicioTxt.getDate());
            String dataStringFim = formatter.format(dataFimTxt.getDate());

            cc = new ContaController();
            cc.resumoMensal(dataStringInicio, dataStringFim);

            TableCellRenderer defaultRenderer = detalhesTabela.getDefaultRenderer(Object.class);
            TableCellRenderer r = new ContasCellRender(defaultRenderer);

            TableCellRenderer r2 = new ContasCellRender(defaultRenderer);
            TableCellRenderer r3 = new ContasCellRender(defaultRenderer);
            TableCellRenderer r4 = new ContasCellRender(defaultRenderer);

            detalhesTabela.getColumnModel().getColumn(0).setPreferredWidth(5);
            detalhesTabela.getColumnModel().getColumn(1).setPreferredWidth(5);
            detalhesTabela.getColumnModel().getColumn(2).setPreferredWidth(180);
            detalhesTabela.getColumnModel().getColumn(3).setPreferredWidth(60);
            detalhesTabela.getColumnModel().getColumn(4).setPreferredWidth(60);
            detalhesTabela.getColumnModel().getColumn(5).setPreferredWidth(60);
            detalhesTabela.getColumnModel().getColumn(6).setPreferredWidth(30);

            detalhesTabela.getColumnModel().getColumn(3).setCellRenderer(r2);
            detalhesTabela.getColumnModel().getColumn(4).setCellRenderer(r3);
            detalhesTabela.getColumnModel().getColumn(5).setCellRenderer(r4);
            detalhesTabela.getColumnModel().getColumn(7).setCellRenderer(r);

            detalhesTabela.getColumnModel().getColumn(7).setCellRenderer(r);
            detalhesTabela.setAutoCreateRowSorter(true);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_carregarBtActionPerformed

    private void fechatBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechatBtActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fechatBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContasResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContasResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContasResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContasResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContasResumo dialog = new ContasResumo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carregarBt;
    private org.jdesktop.swingx.JXDatePicker dataFimTxt;
    private org.jdesktop.swingx.JXDatePicker dataInicioTxt;
    public static javax.swing.JTable detalhesTabela;
    private javax.swing.JButton fechatBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel registroPagos;
    public static javax.swing.JLabel registrosAbertos;
    public static javax.swing.JLabel registrosVencidos;
    public static javax.swing.JLabel totalRegistros;
    public static javax.swing.JLabel valorTotalRecebido;
    public static javax.swing.JLabel valorTotalRegistrosPagos;
    public static javax.swing.JLabel valorTotalRegistrosVencidos;
    public static javax.swing.JLabel valorTotalTudo;
    public static javax.swing.JLabel valorTotalregistrosAbertos;
    // End of variables declaration//GEN-END:variables
}
