/*
 * Copyright (c) 2014 WISE.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    WISE - initial API and implementation and/or initial documentation
 */
package app.view.contas;

import app.controller.AtletaController;
import app.controller.ContaController;
import app.controller.FrequenciaController;
import app.model.atleta.Atleta;
import app.model.tablemodel.ContasReceberTableModel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author WISE
 */
public class ContasView extends javax.swing.JDialog {

    private ContaController cc;
    /**
     * Salva a linha selecionada na tabela Contas receber , pendencias e
     * movimentação.
     */
    public static int linhaSelecionadaCR;
    public static int linhaSelecionadaP;
    public static int linhaSelecionadaM;
    /**
     * Salva o id do registro selecionado.
     */
    public static int idCR;
    public static int idP;
    public static int idM;

    /**
     * Salva a situação da CR ,P e M.
     */
    public static String situacaoCR;
    public static String situacaoP;
    public static String situacaoM;

    /**
     * Salva as datas.
     */
    public static String dataER;
    public static String dataVR;
    public static String dataVP;
    public static String dataEP;
    public static String dataVM;
    public static String dataEM;

    /*
     Valores
     */
    public static float valorR;
    public static float valorP;
    public static float valorM;

    /**
     * NOME
     */
    public static String nomeR;
    public static String nomeP;
    public static String nomeM;

    /**
     * MATRICULA
     */
    public static int matR;
    public static int matP;
    public static int matM;

    private ContasReceberTableModel ctrm;

    /**
     * Creates new form ContasView
     */
    public ContasView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        popularContasReceberTabela();
        popularPendencias();
        popularMovimentacao();

    }

    public ContasView() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        painel = new javax.swing.JTabbedPane();
        contasReceberPainel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contasReceberTabela = new javax.swing.JTable();
        botoesPaine = new javax.swing.JPanel();
        quitarBt = new javax.swing.JButton();
        removerBt = new javax.swing.JButton();
        fecharBt = new javax.swing.JButton();
        atualizarBt = new javax.swing.JButton();
        pesquisarTxt = new javax.swing.JTextField();
        nomeRadio = new javax.swing.JRadioButton();
        situacaoSelect = new javax.swing.JComboBox();
        pesquisarBt = new javax.swing.JButton();
        valorTotalReceberLabel1 = new javax.swing.JLabel();
        valorTotalReceber1 = new javax.swing.JLabel();
        totalRegReceber = new javax.swing.JLabel();
        totalRegReceberLabel = new javax.swing.JLabel();
        pendenciasPainel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendenciasTabela = new javax.swing.JTable();
        botaoPainel2 = new javax.swing.JPanel();
        quitarPendenciasBt = new javax.swing.JButton();
        removerBt2 = new javax.swing.JButton();
        fecharBt2 = new javax.swing.JButton();
        atualizarBt2 = new javax.swing.JButton();
        totalRegPendencias = new javax.swing.JLabel();
        totalRegPendenciasLabel = new javax.swing.JLabel();
        valorTotalPendenciasLabel = new javax.swing.JLabel();
        valorTotalPendencias = new javax.swing.JLabel();
        pesquisarPendenciasTxt = new javax.swing.JTextField();
        nomePendenciasRadio = new javax.swing.JRadioButton();
        matriculaPendenciasRadio = new javax.swing.JRadioButton();
        pesquisarPBt = new javax.swing.JButton();
        movimentacaoPainel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        movimentacaoTabela = new javax.swing.JTable();
        botoesPaine1 = new javax.swing.JPanel();
        quitarBt1 = new javax.swing.JButton();
        removerBt1 = new javax.swing.JButton();
        fecharBt1 = new javax.swing.JButton();
        atualizarBt1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nomeMRadio = new javax.swing.JRadioButton();
        situacaoMSelect = new javax.swing.JComboBox();
        pesquisarMTxt = new javax.swing.JTextField();
        pesquisarMBt = new javax.swing.JButton();
        totalRegistrosLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        matriculaGeralRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Financeiro");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        contasReceberTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        contasReceberTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contasReceberTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contasReceberTabela);

        botoesPaine.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quitarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hand_thumbsup.png"))); // NOI18N
        quitarBt.setText("Quitar");
        quitarBt.setEnabled(false);
        quitarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarBtActionPerformed(evt);
            }
        });

        removerBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-trash.png"))); // NOI18N
        removerBt.setText("Remover");
        removerBt.setEnabled(false);
        removerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBtActionPerformed(evt);
            }
        });

        fecharBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cross.png"))); // NOI18N
        fecharBt.setText("Fechar");
        fecharBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBtActionPerformed(evt);
            }
        });

        atualizarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-refresh3.png"))); // NOI18N
        atualizarBt.setText("Atualizar");
        atualizarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesPaineLayout = new javax.swing.GroupLayout(botoesPaine);
        botoesPaine.setLayout(botoesPaineLayout);
        botoesPaineLayout.setHorizontalGroup(
            botoesPaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quitarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removerBt, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(fecharBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atualizarBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botoesPaineLayout.setVerticalGroup(
            botoesPaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPaineLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(quitarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecharBt))
        );

        buttonGroup1.add(nomeRadio);
        nomeRadio.setSelected(true);
        nomeRadio.setText("Nome");

        situacaoSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Abertas", "Pagas" }));

        pesquisarBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        pesquisarBt.setText("Pesquisar");
        pesquisarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBtActionPerformed(evt);
            }
        });

        valorTotalReceberLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalReceberLabel1.setText("Valor Total:");

        valorTotalReceber1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalReceber1.setForeground(new java.awt.Color(255, 0, 0));
        valorTotalReceber1.setText("0");

        totalRegReceber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegReceber.setText("Total de registros:");

        totalRegReceberLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegReceberLabel.setText("0");

        javax.swing.GroupLayout contasReceberPainelLayout = new javax.swing.GroupLayout(contasReceberPainel);
        contasReceberPainel.setLayout(contasReceberPainelLayout);
        contasReceberPainelLayout.setHorizontalGroup(
            contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contasReceberPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contasReceberPainelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoesPaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contasReceberPainelLayout.createSequentialGroup()
                        .addGroup(contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contasReceberPainelLayout.createSequentialGroup()
                                .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeRadio)
                                .addGap(18, 18, 18)
                                .addComponent(situacaoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisarBt))
                            .addGroup(contasReceberPainelLayout.createSequentialGroup()
                                .addComponent(totalRegReceber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalRegReceberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotalReceberLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotalReceber1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contasReceberPainelLayout.setVerticalGroup(
            contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contasReceberPainelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeRadio)
                    .addComponent(situacaoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(botoesPaine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(contasReceberPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRegReceber)
                    .addComponent(totalRegReceberLabel)
                    .addComponent(valorTotalReceberLabel1)
                    .addComponent(valorTotalReceber1))
                .addContainerGap())
        );

        painel.addTab("Contas a receber", contasReceberPainel);

        pendenciasTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pendenciasTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendenciasTabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(pendenciasTabela);

        botaoPainel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quitarPendenciasBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hand_thumbsup.png"))); // NOI18N
        quitarPendenciasBt.setText("Quitar");
        quitarPendenciasBt.setEnabled(false);
        quitarPendenciasBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarPendenciasBtActionPerformed(evt);
            }
        });

        removerBt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-trash.png"))); // NOI18N
        removerBt2.setText("Remover");
        removerBt2.setEnabled(false);
        removerBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBt2ActionPerformed(evt);
            }
        });

        fecharBt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cross.png"))); // NOI18N
        fecharBt2.setText("Fechar");
        fecharBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBt2ActionPerformed(evt);
            }
        });

        atualizarBt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-refresh3.png"))); // NOI18N
        atualizarBt2.setText("Atualizar");
        atualizarBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botaoPainel2Layout = new javax.swing.GroupLayout(botaoPainel2);
        botaoPainel2.setLayout(botaoPainel2Layout);
        botaoPainel2Layout.setHorizontalGroup(
            botaoPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quitarPendenciasBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removerBt2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(fecharBt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atualizarBt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botaoPainel2Layout.setVerticalGroup(
            botaoPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoPainel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(quitarPendenciasBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarBt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerBt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecharBt2))
        );

        totalRegPendencias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegPendencias.setText("Total de registros:");

        totalRegPendenciasLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegPendenciasLabel.setText("0");

        valorTotalPendenciasLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalPendenciasLabel.setText("Valor Total:");

        valorTotalPendencias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        valorTotalPendencias.setForeground(new java.awt.Color(255, 0, 0));
        valorTotalPendencias.setText("0");

        buttonGroup2.add(nomePendenciasRadio);
        nomePendenciasRadio.setText("Nome");

        buttonGroup2.add(matriculaPendenciasRadio);
        matriculaPendenciasRadio.setSelected(true);
        matriculaPendenciasRadio.setText("Matrícula");

        pesquisarPBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        pesquisarPBt.setText("Pesquisar");
        pesquisarPBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarPBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pendenciasPainelLayout = new javax.swing.GroupLayout(pendenciasPainel);
        pendenciasPainel.setLayout(pendenciasPainelLayout);
        pendenciasPainelLayout.setHorizontalGroup(
            pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendenciasPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendenciasPainelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPainel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pendenciasPainelLayout.createSequentialGroup()
                        .addGroup(pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pendenciasPainelLayout.createSequentialGroup()
                                .addComponent(totalRegPendencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalRegPendenciasLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotalPendenciasLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotalPendencias))
                            .addGroup(pendenciasPainelLayout.createSequentialGroup()
                                .addComponent(pesquisarPendenciasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomePendenciasRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculaPendenciasRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisarPBt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pendenciasPainelLayout.setVerticalGroup(
            pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendenciasPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarPendenciasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePendenciasRadio)
                    .addComponent(matriculaPendenciasRadio)
                    .addComponent(pesquisarPBt))
                .addGap(11, 11, 11)
                .addGroup(pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(botaoPainel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(pendenciasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRegPendencias)
                    .addComponent(totalRegPendenciasLabel)
                    .addComponent(valorTotalPendenciasLabel)
                    .addComponent(valorTotalPendencias))
                .addContainerGap())
        );

        painel.addTab("Pendencias", pendenciasPainel);

        movimentacaoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movimentacaoTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movimentacaoTabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(movimentacaoTabela);

        botoesPaine1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quitarBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hand_thumbsup.png"))); // NOI18N
        quitarBt1.setText("Quitar");
        quitarBt1.setEnabled(false);
        quitarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarBt1ActionPerformed(evt);
            }
        });

        removerBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-trash.png"))); // NOI18N
        removerBt1.setText("Remover");
        removerBt1.setEnabled(false);
        removerBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBt1ActionPerformed(evt);
            }
        });

        fecharBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-cross.png"))); // NOI18N
        fecharBt1.setText("Fechar");
        fecharBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBt1ActionPerformed(evt);
            }
        });

        atualizarBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-refresh3.png"))); // NOI18N
        atualizarBt1.setText("Atualizar");
        atualizarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBt1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboardd.png"))); // NOI18N
        jButton1.setText("Resumo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesPaine1Layout = new javax.swing.GroupLayout(botoesPaine1);
        botoesPaine1.setLayout(botoesPaine1Layout);
        botoesPaine1Layout.setHorizontalGroup(
            botoesPaine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quitarBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(removerBt1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addComponent(fecharBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(atualizarBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botoesPaine1Layout.setVerticalGroup(
            botoesPaine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPaine1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(quitarBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarBt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerBt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fecharBt1))
        );

        buttonGroup3.add(nomeMRadio);
        nomeMRadio.setSelected(true);
        nomeMRadio.setText("Nome");

        situacaoMSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Abertas", "Vencidas", "Pagas" }));

        pesquisarMTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMTxtActionPerformed(evt);
            }
        });

        pesquisarMBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        pesquisarMBt.setText("Pesquisar");
        pesquisarMBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMBtActionPerformed(evt);
            }
        });

        totalRegistrosLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalRegistrosLabel.setText("Total de Registros:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalLabel.setText("0");

        buttonGroup3.add(matriculaGeralRadio);
        matriculaGeralRadio.setText("Matrícula");

        javax.swing.GroupLayout movimentacaoPainelLayout = new javax.swing.GroupLayout(movimentacaoPainel);
        movimentacaoPainel.setLayout(movimentacaoPainelLayout);
        movimentacaoPainelLayout.setHorizontalGroup(
            movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoesPaine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                        .addGroup(movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                                .addComponent(totalRegistrosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalLabel))
                            .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                                .addComponent(pesquisarMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeMRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculaGeralRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(situacaoMSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisarMBt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        movimentacaoPainelLayout.setVerticalGroup(
            movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentacaoPainelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeMRadio)
                    .addComponent(situacaoMSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarMBt)
                    .addComponent(matriculaGeralRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(botoesPaine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(movimentacaoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRegistrosLabel)
                    .addComponent(totalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel.addTab("Movimentação Geral", movimentacaoPainel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBt1ActionPerformed
        popularMovimentacao();
        quitarBt1.setEnabled(false);
        removerBt1.setEnabled(false);

        linhaSelecionadaM = 0;
        idM = 0;
        movimentacaoTabela.clearSelection();
        matM = 0;
    }//GEN-LAST:event_atualizarBt1ActionPerformed

    private void fecharBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBt1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fecharBt1ActionPerformed

    private void removerBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBt1ActionPerformed
        cc = new ContaController();
        if (cc.removerConta(idM) == true) {
            movimentacaoTabela.clearSelection();
            quitarBt1.setEnabled(false);
            removerBt1.setEnabled(false);
        }
    }//GEN-LAST:event_removerBt1ActionPerformed

    private void quitarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarBt1ActionPerformed
        cc = new ContaController();

        if (situacaoM.equals("Pago")) {
            JOptionPane.showMessageDialog(null, "A conta ja está quitada.", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else {

            /*Se o atleta estivar desativado pergunta se deseja ativar*/
            AtletaController ac = new AtletaController();
            if (ac.retornaSituacaoAtleta(matM).equals("N")) {

                int dialogResultado2 = JOptionPane.showConfirmDialog(null, "O atleta está inativo deseja ativalo?");
                if (dialogResultado2 == JOptionPane.YES_OPTION) {
                    if (ac.ativarAtleta(matM) == true) {
                        int dialogResultado3 = JOptionPane.showConfirmDialog(null, "Atleta ativado. Deseja adicioná-lo na ata de presença?");
                        if (dialogResultado3 == JOptionPane.YES_OPTION) {

                            Atleta a = new Atleta();
                            a = ac.retornaAtleta(matM);
                            FrequenciaController fc = new FrequenciaController();
                            fc.addNaFrequencia(a.getId());
                        }
                    }

                }
            }
            /*Quita a conta*/
            if (cc.quitarConta(idM) == true) {
                int dialogResultado = JOptionPane.showConfirmDialog(null, "Deseja gerar um novo lançamento com este atleta?");
                if (dialogResultado == JOptionPane.YES_OPTION) {

                    if (cc.lancamentoRapido(dataVM, valorM, nomeM, String.valueOf(matM), null, "Movimentacao") == true) {
                        JOptionPane.showMessageDialog(null, "Operação concluída.", "Alerta", JOptionPane.INFORMATION_MESSAGE);

                        movimentacaoTabela.setValueAt("Pago", linhaSelecionadaM, 7);
                        quitarBt1.setEnabled(false);
                        removerBt1.setEnabled(false);

                        linhaSelecionadaM = 0;
                        idM = 0;
                        movimentacaoTabela.clearSelection();
                        matM = 0;
                    }
                } else {

                    movimentacaoTabela.setValueAt("Pago", linhaSelecionadaM, 7);
                    quitarBt1.setEnabled(false);
                    removerBt1.setEnabled(false);

                    linhaSelecionadaM = 0;
                    idM = 0;
                    matM = 0;
                    movimentacaoTabela.clearSelection();
                }

            }

        }
    }//GEN-LAST:event_quitarBt1ActionPerformed

    private void movimentacaoTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movimentacaoTabelaMouseClicked
        if (movimentacaoTabela.getModel().getRowCount() > 0) {
            linhaSelecionadaM = movimentacaoTabela.getSelectedRow();
            //  System.err.println(linhaSelecionadaM);
            int coluna = movimentacaoTabela.getSelectedColumn();
            //(int) movimentacaoTabela.getModel().getValueAt(linhaSelecionadaM, 0); antes
            //Pega o ID dentro do Abstra..Model se o abstratic table model sair de sicronia http://stackoverflow.com/questions/4110360/sorting-with-a-custom-abstracttablemodel
            //  movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 0); depois 
            idM = (int) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 0);
            // System.err.println(idM);
            matM = (int) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 1);
            situacaoM = (String) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 7);
            nomeM = (String) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 2);
            dataEM = (String) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 3);
            dataVM = (String) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 4);
            valorM = (float) movimentacaoTabela.getModel().getValueAt(movimentacaoTabela.convertRowIndexToModel(linhaSelecionadaM), 6);
            quitarBt1.setEnabled(true);
            removerBt1.setEnabled(true);

        }
    }//GEN-LAST:event_movimentacaoTabelaMouseClicked

    private void atualizarBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBt2ActionPerformed
        popularPendencias();
        quitarPendenciasBt.setEnabled(false);
        removerBt2.setEnabled(false);
        linhaSelecionadaM = 0;
        idM = 0;
        matM = 0;
        movimentacaoTabela.clearSelection();
    }//GEN-LAST:event_atualizarBt2ActionPerformed

    private void fecharBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBt2ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fecharBt2ActionPerformed

    private void removerBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBt2ActionPerformed
        cc = new ContaController();
        if (cc.removerConta(idP) == true) {
            pendenciasTabela.clearSelection();
            quitarPendenciasBt.setEnabled(false);
            removerBt2.setEnabled(false);
        }
    }//GEN-LAST:event_removerBt2ActionPerformed

    private void quitarPendenciasBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarPendenciasBtActionPerformed
        cc = new ContaController();

        if (situacaoP.equals("Pago")) {
            JOptionPane.showMessageDialog(null, "A conta ja está quitada.", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else {

            /*Se o atleta estivar desativado pergunta se deseja ativar*/
            AtletaController ac = new AtletaController();
            if (ac.retornaSituacaoAtleta(matP).equals("N")) {

                int dialogResultado2 = JOptionPane.showConfirmDialog(null, "O atleta está inativo deseja ativalo?");
                if (dialogResultado2 == JOptionPane.YES_OPTION) {
                    if (ac.ativarAtleta(matP) == true) {
                        int dialogResultado3 = JOptionPane.showConfirmDialog(null, "Atleta ativado. Deseja adicioná-lo na ata de presença?");
                        if (dialogResultado3 == JOptionPane.YES_OPTION) {

                            Atleta a = new Atleta();
                            a = ac.retornaAtleta(matP);
                            FrequenciaController fc = new FrequenciaController();
                            fc.addNaFrequencia(a.getId());
                        }
                    }

                }
            }

            /*Quita*/
            if (cc.quitarConta(idP) == true) {

                int dialogResultado = JOptionPane.showConfirmDialog(null, "Deseja gerar um novo lançamento com este atleta?");
                if (dialogResultado == JOptionPane.YES_OPTION) {

                    if (cc.lancamentoRapido(dataVP, valorP, nomeP, String.valueOf(matP), null, "Pendencias") == true) {
                        JOptionPane.showMessageDialog(null, "Operação concluída.", "Alerta", JOptionPane.INFORMATION_MESSAGE);

                        ctrm = new ContasReceberTableModel();
                        ctrm = (ContasReceberTableModel) pendenciasTabela.getModel();

                        ctrm.removeRow(linhaSelecionadaP);

                        quitarPendenciasBt.setEnabled(false);
                        removerBt2.setEnabled(false);
                        
                        linhaSelecionadaP = 0;
                        idP = 0;
                        matP = 0;
                        situacaoP = "";
                        pendenciasTabela.clearSelection();
                    }
                } else {

                    ctrm = new ContasReceberTableModel();
                    ctrm = (ContasReceberTableModel) pendenciasTabela.getModel();

                    ctrm.removeRow(linhaSelecionadaP);
                    
                    quitarPendenciasBt.setEnabled(false);
                    removerBt2.setEnabled(false);
                    linhaSelecionadaP = 0;
                    idP = 0;
                    matP = 0;
                    situacaoP = "";
                    pendenciasTabela.clearSelection();
                }

            }

        }
        /*  ctrm.removeRow(linhaSelecionadaP);
         pendenciasTabela.remove(linhaSelecionadaP);
         quitarPendenciasBt.setEnabled(false);
         removerBt2.setEnabled(false);
         linhaSelecionadaP = 0;
         idP = 0;
         situacaoP = "";*/
    }//GEN-LAST:event_quitarPendenciasBtActionPerformed

    private void pendenciasTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendenciasTabelaMouseClicked
        if (pendenciasTabela.getModel().getRowCount() > 0) {
            linhaSelecionadaP = pendenciasTabela.getSelectedRow();
            int coluna = pendenciasTabela.getSelectedColumn();

            idP = (int) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 0);
            matP = (int) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 1);
            situacaoP = (String) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 7);
            nomeP = (String) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 2);
            dataEP = (String) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 3);
            dataVP = (String) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 4);
            valorP = (float) pendenciasTabela.getModel().getValueAt(pendenciasTabela.convertRowIndexToModel(linhaSelecionadaP), 6);
            quitarPendenciasBt.setEnabled(true);
            removerBt2.setEnabled(true);
        }
    }//GEN-LAST:event_pendenciasTabelaMouseClicked

    private void atualizarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtActionPerformed
        popularContasReceberTabela();
        linhaSelecionadaCR = 0;
        idCR = 0;
        matR = 0;

        quitarBt.setEnabled(false);
        removerBt.setEnabled(false);
    }//GEN-LAST:event_atualizarBtActionPerformed

    private void fecharBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_fecharBtActionPerformed

    private void removerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBtActionPerformed
        cc = new ContaController();
        if (cc.removerConta(idCR) == true) {
            contasReceberTabela.clearSelection();
            quitarBt.setEnabled(false);
            removerBt.setEnabled(false);
        }
    }//GEN-LAST:event_removerBtActionPerformed

    private void quitarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarBtActionPerformed
        cc = new ContaController();

        if (situacaoCR.equals("Pago")) {
            JOptionPane.showMessageDialog(null, "A conta ja está quitada.", "Alerta", JOptionPane.INFORMATION_MESSAGE);

        } else {

            /*Se o atleta estivar desativado pergunta se deseja ativar*/
            AtletaController ac = new AtletaController();
            if (ac.retornaSituacaoAtleta(matR).equals("N")) {

                int dialogResultado2 = JOptionPane.showConfirmDialog(null, "O atleta está inativo deseja ativalo?");
                if (dialogResultado2 == JOptionPane.YES_OPTION) {
                    if (ac.ativarAtleta(matR) == true) {
                        int dialogResultado3 = JOptionPane.showConfirmDialog(null, "Atleta ativado. Deseja adicioná-lo na ata de presença?");
                        if (dialogResultado3 == JOptionPane.YES_OPTION) {

                            Atleta a = new Atleta();
                            a = ac.retornaAtleta(matR);
                            FrequenciaController fc = new FrequenciaController();
                            fc.addNaFrequencia(a.getId());
                        }
                    }

                }
            }

            /*Quita a conta*/
            if (cc.quitarConta(idCR) == true) {
                contasReceberTabela.clearSelection();
                ctrm = new ContasReceberTableModel();
                ctrm = (ContasReceberTableModel) contasReceberTabela.getModel();

                int dialogResultado = JOptionPane.showConfirmDialog(null, "Deseja gerar um novo lançamento com este atleta?");
                if (dialogResultado == JOptionPane.YES_OPTION) {

                    if (cc.lancamentoRapido(dataVR, valorR, nomeR, String.valueOf(matR), null, "Receber") == true) {
                        JOptionPane.showMessageDialog(null, "Operação concluída.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                        Date date = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        String data = sdf.format(date);
                        ctrm.setValueAt(data + "", linhaSelecionadaCR, 5);
                        ctrm.setValueAt("Pago", linhaSelecionadaCR, 7);

                        linhaSelecionadaCR = 0;
                        idCR = 0;

                        quitarBt.setEnabled(false);
                        removerBt.setEnabled(false);
                        matR = 0;
                    }
                } else {
                    Date date = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    String data = sdf.format(date);
                    ctrm.setValueAt(data + "", linhaSelecionadaCR, 5);
                    ctrm.setValueAt("Pago", linhaSelecionadaCR, 7);

                    linhaSelecionadaCR = 0;
                    idCR = 0;
                    matR = 0;

                    quitarBt.setEnabled(false);
                    removerBt.setEnabled(false);
                }

            }
        }
    }//GEN-LAST:event_quitarBtActionPerformed

    private void contasReceberTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasReceberTabelaMouseClicked
        if (contasReceberTabela.getModel().getRowCount() > 0) {
            linhaSelecionadaCR = contasReceberTabela.getSelectedRow();
            int coluna = contasReceberTabela.getSelectedColumn();

            idCR = (int) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 0);
            matR = (int) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 1);
            situacaoCR = (String) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 7);
            nomeR = (String) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 2);
            dataER = (String) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 3);
            dataVR = (String) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 4);
            valorR = (float) contasReceberTabela.getModel().getValueAt(contasReceberTabela.convertRowIndexToModel(linhaSelecionadaCR), 6);
            quitarBt.setEnabled(true);
            removerBt.setEnabled(true);
        }
    }//GEN-LAST:event_contasReceberTabelaMouseClicked

    private void pesquisarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBtActionPerformed

        String pesquisa = pesquisarTxt.getText();
        String campos = null;
        String situacao;

        if (nomeRadio.isSelected()) {
            campos = "nome";
        }

        situacao = String.valueOf(situacaoSelect.getSelectedIndex());

        switch (situacao) {
            case "1":
                situacao = "A";
                break;
            case "2":
                situacao = "P";
                break;
            case "3":
                situacao = "PG";
                break;

            case "0":
                situacao = "NULL";
                break;
        }

        cc = new ContaController();
        cc.filtrar("receber", pesquisa, campos, situacao, contasReceberTabela);

    }//GEN-LAST:event_pesquisarBtActionPerformed

    private void pesquisarMBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMBtActionPerformed
        String pesquisa = pesquisarMTxt.getText();
        String campos = null;
        String situacao;

        if (nomeMRadio.isSelected()) {
            campos = "nome";
        }

        if (matriculaGeralRadio.isSelected()) {
            campos = "matricula";
        }

        situacao = String.valueOf(situacaoMSelect.getSelectedIndex());

        switch (situacao) {

            case "0":
                situacao = "NULL";
                break;

            case "1":
                situacao = "A";
                break;
            case "2":
                situacao = "P";
                break;
            case "3":
                situacao = "PG";
                break;

        }

        cc = new ContaController();
        cc.filtrar("movimento", pesquisa, campos, situacao, movimentacaoTabela);
    }//GEN-LAST:event_pesquisarMBtActionPerformed

    private void pesquisarMTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMTxtActionPerformed
        pesquisarMBtActionPerformed(evt);
    }//GEN-LAST:event_pesquisarMTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ContasResumo cr = new ContasResumo(null, true);
        cr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pesquisarPBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarPBtActionPerformed
        String pesquisa = pesquisarPendenciasTxt.getText();
        String campos = null;
        String situacao;

        if (nomePendenciasRadio.isSelected()) {
            campos = "nome";
        }
        if (matriculaPendenciasRadio.isSelected()) {
            campos = "matricula";
        }

        cc = new ContaController();
        cc.filtrar("pendente", pesquisa, campos, "P", pendenciasTabela);
    }//GEN-LAST:event_pesquisarPBtActionPerformed

    public void popularContasReceberTabela() {
        cc = new ContaController();
        TableCellRenderer defaultRenderer = contasReceberTabela.getDefaultRenderer(Object.class);
        TableCellRenderer r = new ContasCellRender(defaultRenderer);
        TableCellRenderer r2 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r3 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r4 = new ContasCellRender(defaultRenderer);

        contasReceberTabela.setModel(cc.listaContasReceber());
        contasReceberTabela.getColumnModel().getColumn(0).setPreferredWidth(5);
        contasReceberTabela.getColumnModel().getColumn(1).setPreferredWidth(5);
        contasReceberTabela.getColumnModel().getColumn(2).setPreferredWidth(180);
        contasReceberTabela.getColumnModel().getColumn(3).setPreferredWidth(60); //data emissao
        contasReceberTabela.getColumnModel().getColumn(4).setPreferredWidth(60);
        contasReceberTabela.getColumnModel().getColumn(5).setPreferredWidth(60);
        contasReceberTabela.getColumnModel().getColumn(6).setPreferredWidth(30);

        contasReceberTabela.getColumnModel().getColumn(3).setCellRenderer(r);
        contasReceberTabela.getColumnModel().getColumn(4).setCellRenderer(r3);
        contasReceberTabela.getColumnModel().getColumn(5).setCellRenderer(r4);
        contasReceberTabela.getColumnModel().getColumn(7).setCellRenderer(r2);

        totalRegReceberLabel.setText(String.valueOf(contasReceberTabela.getModel().getRowCount()));
        float valorTotal = 0;
        for (int i = 0; i < contasReceberTabela.getModel().getRowCount(); i++) {
            valorTotal = valorTotal + (float) contasReceberTabela.getValueAt(i, 6);

        }
        DecimalFormat dc = new DecimalFormat("0.00");

        valorTotalReceber1.setText("R$ " + (String.valueOf(dc.format(valorTotal))));

    }

    public void popularPendencias() {
        cc = new ContaController();
        pendenciasTabela.setModel(cc.listaPendencias());
        pendenciasTabela.getColumnModel().getColumn(0).setPreferredWidth(5);
        pendenciasTabela.getColumnModel().getColumn(1).setPreferredWidth(5);
        pendenciasTabela.getColumnModel().getColumn(2).setPreferredWidth(180);
        pendenciasTabela.getColumnModel().getColumn(3).setPreferredWidth(60);
        pendenciasTabela.getColumnModel().getColumn(4).setPreferredWidth(60);
        pendenciasTabela.getColumnModel().getColumn(5).setPreferredWidth(60);
        pendenciasTabela.getColumnModel().getColumn(6).setPreferredWidth(30);

        TableCellRenderer defaultRenderer = pendenciasTabela.getDefaultRenderer(Object.class);
        TableCellRenderer r = new ContasCellRender(defaultRenderer);
        TableCellRenderer r2 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r3 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r4 = new ContasCellRender(defaultRenderer);

        pendenciasTabela.getColumnModel().getColumn(3).setCellRenderer(r2);
        pendenciasTabela.getColumnModel().getColumn(4).setCellRenderer(r3);
        pendenciasTabela.getColumnModel().getColumn(5).setCellRenderer(r4);
        pendenciasTabela.getColumnModel().getColumn(7).setCellRenderer(r);

        totalRegPendenciasLabel.setText(String.valueOf(pendenciasTabela.getModel().getRowCount()));
        float valorTotal = 0;
        for (int i = 0; i < pendenciasTabela.getModel().getRowCount(); i++) {
            valorTotal = valorTotal + (float) pendenciasTabela.getValueAt(i, 6);

        }
        DecimalFormat dc = new DecimalFormat("0.00");

        valorTotalPendencias.setText("R$ " + (String.valueOf(dc.format(valorTotal))));
    }

    public void popularMovimentacao() {
        cc = new ContaController();

        movimentacaoTabela.setModel(cc.listaMovimentacao());
        movimentacaoTabela.getColumnModel().getColumn(0).setPreferredWidth(5);
        movimentacaoTabela.getColumnModel().getColumn(1).setPreferredWidth(5);
        movimentacaoTabela.getColumnModel().getColumn(2).setPreferredWidth(180);
        movimentacaoTabela.getColumnModel().getColumn(3).setPreferredWidth(60);
        movimentacaoTabela.getColumnModel().getColumn(4).setPreferredWidth(60);
        movimentacaoTabela.getColumnModel().getColumn(5).setPreferredWidth(60);
        movimentacaoTabela.getColumnModel().getColumn(6).setPreferredWidth(30);

        TableCellRenderer defaultRenderer = movimentacaoTabela.getDefaultRenderer(Object.class);
        TableCellRenderer r = new ContasCellRender(defaultRenderer);
        TableCellRenderer r2 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r3 = new ContasCellRender(defaultRenderer);
        TableCellRenderer r4 = new ContasCellRender(defaultRenderer);

        movimentacaoTabela.getColumnModel().getColumn(3).setCellRenderer(r2);
        movimentacaoTabela.getColumnModel().getColumn(4).setCellRenderer(r3);
        movimentacaoTabela.getColumnModel().getColumn(5).setCellRenderer(r4);
        movimentacaoTabela.getColumnModel().getColumn(7).setCellRenderer(r);

        totalLabel.setText(String.valueOf(movimentacaoTabela.getModel().getRowCount()));
        movimentacaoTabela.setAutoCreateRowSorter(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ContasView dialog = new ContasView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBt;
    private javax.swing.JButton atualizarBt1;
    private javax.swing.JButton atualizarBt2;
    private javax.swing.JPanel botaoPainel2;
    private javax.swing.JPanel botoesPaine;
    private javax.swing.JPanel botoesPaine1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    public javax.swing.JPanel contasReceberPainel;
    public static javax.swing.JTable contasReceberTabela;
    private javax.swing.JButton fecharBt;
    private javax.swing.JButton fecharBt1;
    private javax.swing.JButton fecharBt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton matriculaGeralRadio;
    private javax.swing.JRadioButton matriculaPendenciasRadio;
    public javax.swing.JPanel movimentacaoPainel;
    public static javax.swing.JTable movimentacaoTabela;
    private javax.swing.JRadioButton nomeMRadio;
    private javax.swing.JRadioButton nomePendenciasRadio;
    private javax.swing.JRadioButton nomeRadio;
    public javax.swing.JTabbedPane painel;
    public javax.swing.JPanel pendenciasPainel;
    public static javax.swing.JTable pendenciasTabela;
    private javax.swing.JButton pesquisarBt;
    private javax.swing.JButton pesquisarMBt;
    private javax.swing.JTextField pesquisarMTxt;
    private javax.swing.JButton pesquisarPBt;
    private javax.swing.JTextField pesquisarPendenciasTxt;
    private javax.swing.JTextField pesquisarTxt;
    private javax.swing.JButton quitarBt;
    private javax.swing.JButton quitarBt1;
    private javax.swing.JButton quitarPendenciasBt;
    private javax.swing.JButton removerBt;
    private javax.swing.JButton removerBt1;
    private javax.swing.JButton removerBt2;
    private javax.swing.JComboBox situacaoMSelect;
    private javax.swing.JComboBox situacaoSelect;
    public static javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalRegPendencias;
    private javax.swing.JLabel totalRegPendenciasLabel;
    private javax.swing.JLabel totalRegReceber;
    private javax.swing.JLabel totalRegReceberLabel;
    private javax.swing.JLabel totalRegistrosLabel;
    private javax.swing.JLabel valorTotalPendencias;
    private javax.swing.JLabel valorTotalPendenciasLabel;
    private javax.swing.JLabel valorTotalReceber1;
    private javax.swing.JLabel valorTotalReceberLabel1;
    // End of variables declaration//GEN-END:variables
}
